### ISSUE TITLE
SketchyBar 2.5.0 failed to build on Apple SDK 10.13

### ISSUE THREAD

**Issue by azuwis** [FelixKratz/SketchyBar#174]
Tried to update sketchybar from 2.4.3 to 2.5.0 for Nix https://github.com/NixOS/nixpkgs/pull/163421, the CI tells build failed for x64 https://logs.nix.ci/?key=nixos/nixpkgs.163421&attempt_id=8c09f774-84f5-49fc-8305-844c64c7ca1b

```
clang src/manifest.m -std=c99 -Wall -DNDEBUG -Ofast -fvisibility=hidden -target x86_64-apple-macos10.13 -F/System/Library/PrivateFrameworks -framework Carbon -framework Cocoa -framework SkyLight  -o bin/sketchybar_x86
In file included from src/manifest.m:45:
src/message.c:538:15: warning: implicit declaration of function 'open_memstream' is invalid in C99 [-Wimplicit-function-declaration]
  FILE* rsp = open_memstream(&response, &length);
              ^
src/message.c:538:9: warning: incompatible integer to pointer conversion initializing 'FILE *' (aka 'struct __sFILE *') with an expression of type 'int' [-Wint-conversion]
  FILE* rsp = open_memstream(&response, &length);
        ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
Undefined symbols for architecture x86_64:
  "_open_memstream", referenced from:
      _handle_message_mach in manifest-e0b4a5.o
ld: symbol(s) not found for architecture x86_64
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [makefile:49: bin/sketchybar_x86] Error 1
error: builder for '/nix/store/vckdfimad38z66vda9zay82c5ngpq9ma-sketchybar-2.5.0.drv' failed with exit code 2;
```

Arm64 works on my own machine.

Nix for macOS x64 use an old SDK 10.13, maybe it's related?

**Comment by FelixKratz** [comment]
POSIX.1-2008 standard functions (such as open_memstream) are available in stdio as of macOS 10.13. Possibly you need
to change the old SDK to something more modern.

Compiling works on both my Big Sur x86 and Monterey arm64 machines. I cannot guarantee support for all lower macOS
versions.

**Comment by azuwis** [comment]
Seems fixed by introducing https://www.piumarta.com/software/memstream/
